Repository tarantool/graphql, pull requests merged in 2018-04, with the labels that each got.

#108 Freeze shard version on 1.2 in CI
  .travis.yml
Labels: bug, infrastructure, testing

#95 WIP simple configuration
  graphql/accessor_general.lua
  graphql/accessor_shard.lua
  graphql/accessor_space.lua
  graphql/config_complement.lua
  graphql/simple_config.lua
  graphql/tarantool_graphql.lua
  graphql/utils.lua
  test/local/complemented_config.result
  test/local/complemented_config.test.lua
  test/local/simple_config.result
  test/local/simple_config.test.lua
  test/local/zero_config.result
  test/local/zero_config.test.lua
  test/shard_no_redundancy/shard_common_simple_config.result
  test/shard_no_redundancy/shard_common_simple_config.test.lua
Labels: enhancement, usability

#119 Support (?i) in regexps
  README.md
  graphql/accessor_general.lua
  test/local/space_pcre.result
  test/local/space_pcre.test.lua
Labels: enhancement

#117 Support avro-schema references for records
  graphql/tarantool_graphql.lua
  test/common/avro_refs.test.lua
  test/common/lua/multirunner.lua
  test/common/lua/test_data_avro_refs.lua
  test/common/lua/test_data_nested_record.lua
  test/common/nested_record.test.lua
  test/common/suite.cfg
  test/common/suite.ini
  test/utils.lua
Labels: enhancement

#126 Support UTF-8 in regexps
  graphql/accessor_general.lua
  test/space/pcre.result
  test/space/pcre.test.lua
  test/testdata/common_testdata.lua
Labels: customer, enhancement

#136 Allow to reproduce shard assertion fail
  test/testdata/nullable_index_testdata.lua
Labels: code health
