Repository tarantool/graphql, pull requests merged in 2018-09, with the labels that each got.

#215 Do not hide a field with a connection
  graphql/convert_schema/schema.lua
  test/extra/connections_do_not_hide_fields.test.lua
Labels: customer

#219 Make shard optional
  graphql/accessor_shard_cache.lua
  test/extra/no_shard/shard.lua
  test/extra/shard_optional.lua
  test/test_utils.lua
Labels: bug, customer, regression

#222 Describe query AST format in validate.lua
  graphql/core/parse.lua
  graphql/core/validate.lua
Labels: code health

#209 graphql: implement c-style expressions parser
  graphql/accessor_general.lua
  graphql/convert_schema/schema.lua
  graphql/core/parse.lua
  graphql/core/rules.lua
  graphql/core/util.lua
  graphql/core/validate.lua
  graphql/expressions.lua
  graphql/extend_ast.lua
  graphql/gen_arguments.lua
  graphql/impl.lua
  graphql/utils.lua
  test/common/expressions.test.lua
  test/common/introspection.test.lua
  test/unit/expr_execute.test.lua
  test/unit/expr_tree.test.lua
  test/unit/suite.ini
Labels: enhancement

#238 Pass limit to storages when no filters are given
  graphql/accessor_general.lua
  graphql/core/rules.lua
  test/common/gh-237-pass-limit-when-no-filters.test.lua
  test/test_utils.lua
Labels: enhancement

#241 expressions: fix '<=' evaluation
  graphql/expressions.lua
Labels: bug
