Repository tarantool/graphql, pull requests merged in 2018-03, with the labels that each got.

#67 Nullable 1:1 connections
  graphql/tarantool_graphql.lua
  test/local/space_nullable_1_1_conn.result
  test/local/space_nullable_1_1_conn.test.lua
  test/shard_no_redundancy/shard_nullable_1_1_conn.result
  test/shard_no_redundancy/shard_nullable_1_1_conn.test.lua
  test/shard_redundancy/nullable_1_1_conn.result
  test/shard_redundancy/nullable_1_1_conn.test.lua
  test/testdata/nullable_1_1_conn_testdata.lua
Labels: enhancement, prio1

#74 PCRE matching of string fields
  README.md
  graphql/accessor_general.lua
  graphql/core/util.lua
  graphql/core/validate.lua
  graphql/tarantool_graphql.lua
  graphql/utils.lua
  test/local/space_compound_index.result
  test/local/space_pcre.result
  test/local/space_pcre.test.lua
  test/shard_no_redundancy/shard_compound_index.result
  test/shard_redundancy/shard_compound_index.result
  test/testdata/common_testdata.lua
  test/testdata/compound_index_testdata.lua
Labels: enhancement, prio1

#80 Enable parallel testing
  test/common/suite.ini
  test/extra/suite.ini
  test/local/suite.ini
  test/shard_no_redundancy/suite.ini
  test/shard_redundancy/suite.ini
Labels: testing

#76 add simple tests for @skip and @include directives
  test/local/directives.result
  test/local/directives.test.lua
Labels: prio1, testing
